build:
  command: "/bin/bash -l -c 'npm i && node_modules/.bin/gulp prod'"

frontend:
  command: "/bin/bash -l -c 'npm start'"
  environment:
    NODE_ENV: "production"
    DOMAIN_HOST: "localhost:3000"
  ports:
    - "3000:3000"
